### PR TITLE
prevent error if string only has 1 or 2 octets

### PR DESCRIPTION
**Pull request by lynzt**
Code hard fails if passed string doesn't have at least 2 elements after split...

Prevent hard fail...

### CODE REVIEW

**Comment by lynzt** [comment]
@mike-lang quick fix to prevent cms from bombing when user enters a string as an ip...

**Comment by mike-lang** [comment]
LGTM

**Comment by mike-lang** [comment]
I just merged this and then realized that it's missing a version number bump.  I'll go ahead and add that real quick

**Comment by mike-lang** [comment]
@lynzt Ok this code is now available as version v0.2.2

**Pull request merged**
